services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: unless-stopped
    expose:
      - 8581
    volumes:
      - ./homebridge/config.json:/homebridge/config.json
      - ./homebridge/accessories.json:/homebridge/accessories.json
      - ./homebridge/persist:/homebridge/persist
      - ./homebridge/plugins:/homebridge/plugins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homebridge.rule=Host(`homelab.local`) && PathPrefix(`/homebridge`)"
      - "traefik.http.routers.homebridge.entrypoints=websecure"
      - "traefik.http.routers.homebridge.tls=true"
      - "traefik.http.services.homebridge.loadbalancer.server.port=8581"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"